name: Next.js CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 # Upgrade to the latest version supporting Node.js 20

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 # Upgrade to the latest version supporting Node.js 20
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # - name: Lint code
      #   run: npm run lint

      - name: Build project
        run: npm run build

      - name: Test project
        run: npm test

      - name: Cache Next.js build artifacts
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
