
name: Next.js CI/CD

on:
  push:
    branches: [ "master" ] # Trigger the workflow on pushes to the main branch
  pull_request:
    branches: [ "master" ] # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Test with Node.js 20.x

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Cache npm dependencies to speed up builds

      - name: Install dependencies
        run: npm ci # Clean install dependencies

      - name: Lint code
        run: npm run lint # Run linting step, assuming a `lint` script is in `package.json`

      - name: Build project
        run: npm run build # Build the Next.js project

      - name: Test project
        run: npm test # Run tests after building the project

      - name: Cache Next.js build artifacts
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Upload production artifacts (optional)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: .next # Upload the `.next` folder for preview or deployment
